#!/bin/bash


#Version
VERSION=1.10.2

#Settings
USECMD=yt-dlp
COOKIEDIR=$HOME"/Documents/cookies/"
MAXTHREAD=5
WEBSITE=ytb
PRFNUM=3
IPv="-6"

#yt-dlp
ytdlp_MV="yt-dlp -i --write-thumbnail --write-description --write-info-json --write-playlist-metafiles --write-comments --write-sub --all-subs --write-annotations --add-metadata --limit-rate 64M"
# ytdlp_MV="yt-dlp -i --write-thumbnail --write-description --write-info-json --write-playlist-metafiles --write-comments --write-sub --all-subs --write-annotations --add-metadata -f bestvideo+bestaudio --throttled-rate 1M --limit-rate 64M"
ytdlp_FORMAT="bestvideo+bestaudio"
ytdlp_AD="yt-dlp -i --throttled-rate 1M -f bestaudio -x --audio-format"
ytdlp_NICONICO="yt-dlp -i --write-thumbnail --write-description --write-info-json --write-playlist-metafiles --write-comments --write-sub --sub-lang live_chat -f best --throttled-rate 1M --limit-rate 64M"
ytdlp_TWITCH="yt-dlp -i --write-thumbnail --write-description --write-info-json --write-playlist-metafiles --write-comments --write-sub --all-subs --write-annotations --add-metadata --throttled-rate 1M --limit-rate 64M"
ytdlp_TWICAS="yt-dlp -i --throttled-rate 1M --limit-rate 64M"
#ytarchive
ytarchive="ytarchive --add-metadata -k --save -t -r 15 -trace -v --vp9 --write-description --write-thumbnail"



#Help display
function usage {
	cat <<EOM

Usage: $(basename "$0") [OPTION] URL
Usage: cat hoge.txt | $(basename "$0") [OPTION]

Version: $VERSION

[Need software]
    yt-dlp, ytarchive, git, screen

	yt-dlp:					https://github.com/yt-dlp/yt-dlp
	ytarchive:				https://github.com/Kethsar/ytarchive

[OPTION]
  -1, --yt-dlp				Use yt-dlp(default)_!!Insert this option at the beginning!!.

  -2, --ytarchive			Use ytarchive(ytbLive(Stream)only)_!!Insert this option at the beginning!!.

  -v4						Force IPv4.
  -v6						Force IPv6.
							(default): $IPv

  -a FORMAT,
  --audio=FORMAT			Specify this option when you want to download only the AUDIO.	
							FORMAT: best, m4a, mp3
							(default): best
							m4a, mp3 are conveted from best.

  -c COOKIE,
  --cookie=COOKIE			The name of the cookie to use(for YouTube).

  -d DIR, --dir=DIR			Directory for download.

  -f, --format=DL-FORMAT		Select Download format.
					(default); $ytdlp_FORMAT

  -h, --help				Display usage.

  -i						Display the command before execution.

  -L, --loop				Loop execution of the command with the same options.

  -S SESSIONNAME,
  --screen=SESSIONNAME		Execute the command in a screen session.

  -w WEBSITE,
  --website=WEBSITE			Select the name for download website.
							(default): $WEBSITE
							ytb(YouTube), twitch, niconico, twicas
							!! "twicas" is only download recorded data. !!

  -p PROFILE,
  --profile=PROFILE			Select the name format used when saving the video.
							(default): $PRFNUM
							1: title_[ID].ext
							2: title.ext
							3: date-title / title_[ID].ext
							4: date-title-channel_[channelID] / title_[ID].ext
							5: title-channel_[channelID] / title_[ID].ext
							6: channel_[channelID] / date-title / title_[ID].ext
							7: date-[ID] / title.ext
							8: date-[ID] / title / ID.ext
							9: date-[ID] / ID.ext

  -U, --upgrade				Upgrade this program(Requires "root").

  --user=USER				Username or Mail(for NicoVideo).

  --pass=PASSWORD			Password(for NicoVideo).

EOM
}


# When did not enter any arguments.
if [ $# = 0 ]; then
    usage
    exit 1
fi

# Read arguments
while (( $# > 0 ))
do
    case $1 in
	   -1 | --yt-dlp )
		USECMD=yt-dlp
		;;
	   -2 | --ytarchive )
		USECMD=ytarchive
		ytarcQL=best
		;;
	   -v4 )
		IPv="-4"
		;;
	   -v6 )
		IPv="-6"
		;;
	   -a | --audio | --audio=*? )
		case "$USECMD" in
			"yt-dlp" ) 
			    if [[ "$1" =~ ^--audio=* ]]; then 
		    		AUDIOFMT=$(echo $1 | sed -e 's/^--audio=//')
			    elif [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
		    		AUDIOFMT=best
			    else
		    		AUDIOFMT=$2
		    		shift
			    fi
			;;
			"ytarchive" ) ytarcQL=audio_only ;;
		esac
	        ;;
	    -c | --cookie | --cookie=*? )
	        if [[ "$1" =~ ^--cookie= ]]; then
		    USECOOKIE="--cookies "$COOKIEDIR$(echo $1 | sed -e 's/^--cookie=//')
		elif [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
		    echo "'cookie' requires an argument."
		    exit 1
		else
		    USECOOKIE="--cookies "$COOKIEDIR$2
		    shift
		fi
		;;
            -d | --dir | --dir=*? )
	        if [[ "$1" =~ ^--dir= ]]; then
		    DLDIR=$(echo $1 | sed -e 's/^--dir=//')
		elif [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
		    echo "'dir' requires an argument."
		    exit 1
		else
		    DLDIR=$2
		    shift
		fi
		;;
	    -f | --format | --format=*? )
	        if [[ "$1" =~ ^--format= ]]; then
		    ytdlp_FORMAT="-f "$(echo $1 | sed -e 's/^--format=//')
		elif [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
		    echo "'format' requires an argument."
		    exit 1
		else
		    ytdlp_FORMAT="-f "$2
		    shift
		fi
		;;
	    -h | --help )
		    usage
		    exit 1
		;;
	    -i )
		SHOWCMD=1
		;;
	    -w | --website | --website=*? )
	        if [[ "$1" =~ ^--website=* ]]; then 
		    WEBSITE=$(echo $1 | sed -e 's/^--website=//')
		elif [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
	            echo "'website' requires an argument."
                    exit 1
		else
		    WEBSITE=$2
		    shift
		fi
	        ;;

#	    -L | --loop )

#		-S | --screen | --screen=*? )


	    -p | --profile | --profile=*? )
		if [[ "$1" =~ ^--profile= ]]; then
                    PRFNUM=$(echo $1 | sed -e 's/^--profile=//')
                elif [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
		    PRFNUM="1"
                else
                    PRFNUM="$2"
                    shift
                fi
                ;;
	    -U | --upgrade )
		echo "Updating..." &&
		rm -fr $HOME/Download/$(basename "$0") &&
		git clone https://github.com/mikan010/ytdl-easy $HOME/Download/$(basename "$0") &&
		cp $HOME/Download/$(basename "$0")/$(basename "$0") /usr/local/bin/ &&
		echo "Complete."
		exit 1
		;;
	    --user | --user= )
		if [[ "$1" =~ ^--user= ]]; then
                    USER="-u "$(echo $1 | sed -e 's/^--user=//')
                elif [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
                    echo "'user' requires an argument."
                    exit 1
                else
                    USER="-u "$2
                    shift
                fi
		;;
	    --pass | --pass= )
		if [[ "$1" =~ ^--pass= ]]; then
                    PASS="-p "$(echo $1 | sed -e 's/^--pass=//')
                elif [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
                    echo "'user' requires an argument."
                    exit 1
                else
                    PASS="-p "$2
                    shift
                fi
		;;
	    -* )
	        echo "Illegal option -- '$(echo $1 | sed 's/^-*//')'."
		echo ""
		usage
		exit 1
		;;
	    * )
	        if [[ -n "$ARG1" ]]; then
		    echo "Too many arguments."
		    exit 1
		elif [[ "$1" != http* ]]; then
		    echo "$1" "is not URL."
		    exit 1
		else
		    ARG1="$1"
		fi
		;;
    esac
    shift
done


# Confirm the file name.
case "$PRFNUM" in
	"1" ) PRF='%(title)s_[%(id)s].%(ext)s' ;;
	"2" ) PRF='%(title)s.%(ext)s' ;;
        "3" ) PRF='%(release_date,upload_date|Unknown)s-%(title)s/%(title)s_[%(id)s].%(ext)s' ;;
	"4" ) PRF='%(release_date,upload_date|Unknown)s-%(title)s-%(channel)s_[%(channel_id)s]/%(title)s_[%(id)s].%(ext)s' ;;
        "5" ) PRF='%(title)s-%(channel)s_[%(channel_id)s]/%(title)s_[%(id)s].%(ext)s' ;;
	"6" ) PRF='%(channel)s_[%(channel_id)s]/%(release_date,upload_date|Unknown)s-%(title)s/%(title)s_[%(id)s].%(ext)s' ;;
	"7" ) PRF='%(release_date,upload_date|Unknown)s-[%(id)s]/%(title)s.%(ext)s' ;;
	"8" ) PRF='%(release_date,upload_date|Unknown)s-[%(id)s]/%(title)s/%(id)s.%(ext)s' ;;
	"9" ) PRF='%(release_date,upload_date|Unknown)s-[%(id)s]/%(id)s.%(ext)s' ;;
	* )
	    echo $PRFNUM "is not supported Profile number (option: -p,--profile)."
	    exit 1
	;;
esac
if [[ "$USECMD" = ytarchive ]]; then
    case "$PRFNUM" in
        "3" ) PRF='%(upload_date)s-%(title)s/%(title)s_[%(id)s]' ;;
	"4" ) PRF='%(upload_date)s-%(title)s-%(channel)s_[%(channel_id)s]/%(title)s_[%(id)s]' ;;
	"6" ) PRF='%(channel)s_[%(channel_id)s]/%(upload_date)s-%(title)s/%(title)s_[%(id)s]' ;;
	"7" ) PRF='%(upload_date)s-[%(id)s]/%(title)s' ;;
	"8" ) PRF='%(upload_date)s-[%(id)s]/%(title)s/%(id)s' ;;
	"9" ) PRF='%(upload_date)s-[%(id)s]/%(id)s' ;;
    esac
fi

# Create commands.
if [[ -n "$AUDIOFMT" ]]; then
    case "$USECMD" in
	"yt-dlp" ) EXECCMD="$ytdlp_AD $AUDIOFMT $IPv -o $PRF $USECOOKIE" ;;
	"ytarchive" ) EXECCMD="$ytarchive $IPv -o $PRF $USECOOKIE ";;
    esac
else
    case "$USECMD" in
	"yt-dlp" )
    	    case "$WEBSITE" in
	    	"ytb" ) EXECCMD="$ytdlp_MV $ytdlp_FORMAT $IPv -o $PRF $USECOOKIE" ;;
	    	"twitch" ) EXECCMD="$ytdlp_TWITCH $IPv -o $PRF" ;;
	    	"niconico" ) EXECCMD="$ytdlp_NICONICO $IPv -o $PRF $USER $PASS" ;;
		"twicas" ) EXECCMD="$ytdlp_TWICAS -o $PRF" ;;
            esac
	;;
	"ytarchive" ) EXECCMD="$ytarchive $IPv -o $PRF $USECOOKIE";;
    esac
fi

# Change directory for DL
cd "$DLDIR"


# DL from argument
if [[ -n "$ARG1" ]]; then
    if [[ -n "$SHOWCMD" ]]; then
	echo $EXECCMD $ARG1 $ytarcQL
	exit 1
    else
	$EXECCMD $ARG1 $ytarcQL
	exit 1
    fi
# DL from stdin
else
	if [[ -n "$SHOWCMD" ]]; then
	    cat | xargs -n 1 -IXXX echo $EXECCMD XXX $ytarcQL
	    exit 1
	else
	    cat | xargs -n 1 -P $MAXTHREAD -IXXX $EXECCMD XXX $ytarcQL
	    exit 1
	fi
fi
